[build]
  command = "cd examples/example-svelte-routing && npm i && npm run build"
  publish = "examples/example-svelte-routing/public"

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200